name: Continuous Delivery

on:
  push:
    branches:
      - master

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - run: |
          python -m pip install --upgrade pip
          pip install websockets
      - name: Generate ws key
        run: |
          echo "Generating ws key..."
          echo "Key generated."