name: Continuous Integration
run-name: ${{ github.event_name }} - ${{ github.actor }}

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job started"
      - name: Checkout code
        uses: actions/checkout@v2
      - run: echo "Code checked out"
      - run: echo "Setting up Python 3.13"
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - run: echo "Python 3.13 set up"
      - run: echo "Linting code"
      - name: Lint code
        uses: advanced-security/python-lint-code-scanning-action@v1.1.2
        with:
          linter: pylint

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pip install pytest pytest-cov pytest-asyncio
          pytest tests/test.py --doctest-modules --junitxml=junit-results.xml --cov=src --cov-report=xml --cov-report=html --cov-report=term-missing